import { AntdFile } from "@/services/types";
import { Base, PaginationRequest } from "@/types";

export interface ProductSize extends Base {
  name: string;
  unit: string;
  description: string;
  value: string;
  file_path: string;
}

// Generated by https://quicktype.io

export interface ProductSizeInput {
  desc: string;
  file_path: string;
  name: string;
  unit: string;
  value: string;
  file: AntdFile[];
}

export interface ProductSizeFilter extends PaginationRequest {
  created_at?: string[];
  description?: string;
  name?: string;
  unit?: string;
  value?: string;
}
